
INHERIT += "externalsrc"
EXTERNALSRC_pn-westeros = "${ROOT_PATH}/components/opensource/westeros"
EXTERNALSRC_pn-westeros-sink = "${ROOT_PATH}/components/opensource/westeros/rpi/westeros-sink"
EXTERNALSRC_pn-westeros-simpleshell = "${ROOT_PATH}/components/opensource/westeros/simpleshell"
EXTERNALSRC_pn-westeros-simplebuffer = "${ROOT_PATH}/components/opensource/westeros/simplebuffer"
EXTERNALSRC_pn-westeros-render-dispmanx = "${ROOT_PATH}/components/opensource/westeros/rpi/westeros-render-dispmanx"
EXTERNALSRC_pn-westeros-soc-rpi = "${ROOT_PATH}/components/opensource/westeros/rpi"
